export const videoData = [
  {
    id: 12345,
    videoImage:
      "https://cdn.thewirecutter.com/wp-content/media/2022/07/laptop-under-500-2048px-acer-1.jpg",
    videoTime: "5:38",
    videoDescription:
      "Inspiron 14 Laptop | Inspiron 14 Laptop | Inspiron 14 Laptop",
    views: "2k",
    hoursAgo: "5 hours ago",
    status: "Recent",
    likes: [1, 2, 3],
    dislikes: [],
    date: "15/04/2023",
  },
  {
    id: 123420,
    videoImage:
      "https://cdn.thewirecutter.com/wp-content/media/2022/07/laptop-under-500-2048px-acer-1.jpg",
    videoTime: "5:38",
    videoDescription: "Inspiron 19 Laptop",
    views: "2k",
    hoursAgo: "5 hours ago",
    status: "Oldest",
  },
  {
    id: 123875,
    videoImage:
      "https://cdn.thewirecutter.com/wp-content/media/2022/07/laptop-under-500-2048px-acer-1.jpg",
    videoTime: "5:38",
    videoDescription: "Inspiron 12 Laptop",
    views: "2k",
    hoursAgo: "5 hours ago",
    status: "Recent",
  },
  {
    id: 12455,
    videoImage:
      "https://cdn.thewirecutter.com/wp-content/media/2022/07/laptop-under-500-2048px-acer-1.jpg",
    videoTime: "5:38",
    videoDescription: "Inspiron 13 Laptop",
    views: "2k",
    hoursAgo: "5 hours ago",
    status: "Popular",
  },
  {
    id: 12395,
    videoImage:
      "https://cdn.thewirecutter.com/wp-content/media/2022/07/laptop-under-500-2048px-acer-1.jpg",
    videoTime: "5:38",
    videoDescription: "Inspiron 16 Laptop",
    views: "2k",
    hoursAgo: "5 hours ago",
    status: "Oldest",
  },
  {
    id: 12323,
    videoImage:
      "https://cdn.thewirecutter.com/wp-content/media/2022/07/laptop-under-500-2048px-acer-1.jpg",
    videoTime: "5:38",
    videoDescription: "Inspiron 18 Laptop",
    views: "2k",
    hoursAgo: "5 hours ago",
    status: "Recent",
  },
  {
    id: 12334,
    videoImage:
      "https://cdn.thewirecutter.com/wp-content/media/2022/07/laptop-under-500-2048px-acer-1.jpg",
    videoTime: "5:38",
    videoDescription: "Inspiron 17 Laptop",
    views: "2k",
    hoursAgo: "5 hours ago",
    status: "Popular",
  },
];

export const photoData = [
  {
    id: 1,
    image: require("../../../assets/images/photo1.png"),
  },
  {
    id: 2,
    image: require("../../../assets/images/photo2.png"),
  },
  {
    id: 3,
    image: require("../../../assets/images/photo3.png"),
  },
  {
    id: 4,
    image: require("../../../assets/images/photo4.png"),
  },
  {
    id: 5,
    image: require("../../../assets/images/photo5.png"),
  },
];
export const statusData = [];
export const reviewData = [];
export const pollData = [];

export const postList = [
  {
    profileImage: require("../../../assets/images/person1.png"),
    mainImage: require("../../../assets/images/photo1.png"),
    title: "Darrell Steward",
    subtitle: "100K Followers • 1 week ago ",
    likes: "70k",
    dislikes: "265",
    add: "165",
    view: "2.6M",
    content:
      "iPhone 13 Pro Unboxing & First Look - The Fresh iPhone Experience",
    pollContent: [
      {
        id: "1",
        image: require("../../../assets/images/phone1.png"),
        topic: "Iphone 13 pro",
        vote: "16%",
      },
      {
        id: "2",
        image: require("../../../assets/images/phone2.png"),
        topic: "Samsung Galaxy S21 FE ",
        vote: "10%",
      },
      {
        id: "3",
        image: require("../../../assets/images/phone3.png"),
        topic: "OnePlus 10 Pro",
        vote: "8%",
      },
      {
        id: "4",
        image: require("../../../assets/images/phone4.png"),
        topic: "Google Pixel 6",
        vote: "12%",
      },
    ],
    poll: false,
    swiper: false,
    video: true,
    post: false,
    review: false,
    watched: false,
    comments: [
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
    ],
  },
  {
    profileImage: require("../../../assets/images/person3.png"),
    mainImage: require("../../../assets/images/photo1.png"),
    title: "Albert Flores",
    subtitle: "48K Followers • 1 week ago ",
    likes: "30k",
    dislikes: "265",
    add: "165",
    view: "2.6M",
    content:
      "MacBook Air (M2 2022) Review: is it the Best Air Yet? #macbookairm2",
    pollContent: [],
    poll: false,
    swiper: true,
    review: false,
    post: false,
    video: true,
    watched: true,
    comments: [
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
    ],
  },
  {
    profileImage: require("../../../assets/images/mkbhd.png"),
    mainImage: require("../../../assets/images/photo1.png"),
    title: "MKBHD",
    subtitle: "30K Followers • 1 week ago ",
    likes: "24k",
    dislikes: "265",
    add: "165",
    view: "2.6M",
    content:
      "Overall not a ton of design innovation that's for sure. No folding screens , no blazing fast charging, etc. But a lot of refinement stuff for pro iPhone again, and a world class chip. Overall not a ton of design. #iphone14pro",
    pollContent: [],
    poll: false,
    review: false,
    video: false,
    post: true,
    swiper: false,
    watched: false,
    comments: [
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
    ],
  },
];

export const pollContent = [
  {
    profileImage: require("../../../assets/images/person1.png"),
    mainImage: null,
    title: "MKBHD",
    subtitle: "25K Followers • 1 week ago ",
    likes: "11k",
    dislikes: "265",
    add: "165",
    view: "2.6M",
    content: "Which one of the Smart phone has best Battery and Processor?",
    poll: true,
    pollContent: [
      {
        id: "1",
        image: require("../../../assets/images/phone1.png"),
        topic: "Iphone 13 pro",
        vote: "16%",
      },
      {
        id: "2",
        image: require("../../../assets/images/phone2.png"),
        topic: "Samsung Galaxy S21 FE ",
        vote: "10%",
      },
      {
        id: "3",
        image: require("../../../assets/images/phone3.png"),
        topic: "OnePlus 10 Pro",
        vote: "8%",
      },
      {
        id: "4",
        image: require("../../../assets/images/phone4.png"),
        topic: "Google Pixel 6",
        vote: "12%",
      },
    ],
    swiper: false,
    review: false,
    post: true,
    video: false,
    watched: false,
    comments: [
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
    ],
  },
  {
    profileImage: require("../../../assets/images/person1.png"),
    mainImage: null,
    title: "MKBHD",
    subtitle: "25K Followers • 1 week ago ",
    likes: "11k",
    dislikes: "265",
    add: "165",
    view: "2.6M",
    content: "Which one of the Smart phone has best Battery and Processor?",
    poll: true,
    pollContent: [
      {
        id: "1",
        image: require("../../../assets/images/phone1.png"),
        topic: "Iphone 13 pro",
        vote: "16%",
      },
      {
        id: "2",
        image: require("../../../assets/images/phone2.png"),
        topic: "Samsung Galaxy S21 FE ",
        vote: "10%",
      },
      {
        id: "3",
        image: require("../../../assets/images/phone3.png"),
        topic: "OnePlus 10 Pro",
        vote: "8%",
      },
      {
        id: "4",
        image: require("../../../assets/images/phone4.png"),
        topic: "Google Pixel 6",
        vote: "12%",
      },
    ],
    swiper: false,
    review: false,
    post: true,
    video: false,
    watched: false,
    comments: [
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
    ],
  },
  {
    profileImage: require("../../../assets/images/person1.png"),
    mainImage: null,
    title: "MKBHD",
    subtitle: "25K Followers • 1 week ago ",
    likes: "11k",
    dislikes: "265",
    add: "165",
    view: "2.6M",
    content: "Which one of the Smart phone has best Battery and Processor?",
    poll: true,
    pollContent: [
      {
        id: "1",
        image: require("../../../assets/images/phone1.png"),
        topic: "Iphone 13 pro",
        vote: "16%",
      },
      {
        id: "2",
        image: require("../../../assets/images/phone2.png"),
        topic: "Samsung Galaxy S21 FE ",
        vote: "10%",
      },
      {
        id: "3",
        image: require("../../../assets/images/phone3.png"),
        topic: "OnePlus 10 Pro",
        vote: "8%",
      },
      {
        id: "4",
        image: require("../../../assets/images/phone4.png"),
        topic: "Google Pixel 6",
        vote: "12%",
      },
    ],
    swiper: false,
    review: false,
    post: true,
    video: false,
    watched: false,
    comments: [
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
      {
        profileImage: require("../../../assets/images/person5.png"),
        title: "Darrell Steward",
        subtitle: "1 week ago ",
        likes: "70k",
        dislikes: "265",
        add: "165",
        content: "Yeah... It's good review. I found your review helpful",
        replies: [
          {
            profileImage: require("../../../assets/images/person3.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
          {
            profileImage: require("../../../assets/images/unknown.png"),
            title: "Darrell Steward",
            subtitle: "1 week ago ",
            likes: "70k",
            dislikes: "265",
            add: "165",
            content: "Yeah... It's good review. I found your review helpful",
          },
        ],
      },
    ],
  },
];

export const productShowed = [
  {
    id: 1,
    image: require("../../../assets/images/photo1.png"),
    name: "APPLE iPhone 13 Pro (Silver, 128 GB)",
    star: "9.1",
    reviews: "2,987",
    originalPrice: "52369",
    discountedPrice: "45678",
  },
  {
    id: 2,
    image: require("../../../assets/images/photo1.png"),
    name: "APPLE iPhone 13 Pro (Silver, 128 GB)",
    star: "9.1",
    reviews: "2,987",
    originalPrice: "52369",
    discountedPrice: "45678",
  },
  {
    id: 3,
    image: require("../../../assets/images/photo1.png"),
    name: "APPLE iPhone 13 Pro (Silver, 128 GB)",
    star: "9.1",
    reviews: "2,987",
    originalPrice: "52369",
    discountedPrice: "45678",
  },
  {
    id: 4,
    image: require("../../../assets/images/photo1.png"),
    name: "APPLE iPhone 13 Pro (Silver, 128 GB)",
    star: "9.1",
    reviews: "2,987",
    originalPrice: "52369",
    discountedPrice: "45678",
  },
  {
    id: 5,
    image: require("../../../assets/images/photo1.png"),
    name: "APPLE iPhone 13 Pro (Silver, 128 GB)",
    star: "9.1",
    reviews: "2,987",
    originalPrice: "52369",
    discountedPrice: "45678",
  },
];

export const filterOptions = [
  {
    id:1,
    name:"Back Camera"
  },
  {
    id:2,
    name:"Front Camera"
  },
  {
    id:3,
    name:"Display"
  },
  {
    id:4,
    name:"RAM"
  },
]